### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-sundews#1]
## User Story
As a user, when I navigate to your site, I should see a navbar.

## AC
**Given** A user navigates to your page
**Then** they should see a navbar
**And** it should have an application logo
**And** it should have an input field
**And** it should have a clear button
**And** it should remain at the top of the screen if the page scrolls

## Dev Notes
Using bootstrap create a  `fixed to the top` navbar.
Logo fixed to the left of the navbar. 
`5 User names` listed across the top center of the navbar with `radio buttons` next to each user name and circle image above the user name and `radio buttons`. Users will be listed in an array of 
Below the 5 user names will be a bootstrap form input section.  In the placeholder text it will say "Type message here and press enter".  That message will then be added to the data seed array. 
At the top right corner of the screen include a `button` labeled `clear` that will clear the chat dialog.
On the right side of the screen after the message bar and radio button user add a `checkbox` option for a `dark theme` and a `checkbox` option for a `large text` option

**Comment by sarahholder** [comment]
![image](https://user-images.githubusercontent.com/59459651/76356406-e4909400-62e3-11ea-8497-1b33d2dc5dcc.png)

**Comment by sarahholder** [comment]
`'<a class="navbar fixed-top navbar-light bg-light">fixed top navbar</a>'`

**Comment by sarahholder** [comment]
```<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>

**Comment by sarahholder** [comment]
`<input type="checkbox" aria-label="Checkbox for following text input">`
