### ISSUE TITLE
Add Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-sundews#13]
## User Story
As a user, I should be able to add messages by clicking enter.

## AC
**Given** A user navigates to your page
**Then** they type in the input field
**And** when they hit enter a new message should be created
**And** the message should show up in the new chat window

## Dev Notes
* In the function that builds the navbar, add a unique id to the Input message field. 
* Create component `addMessage` folder with the corresponding `addMessage` .js and .scss files. 
* In the `addMessage.js` file, write an `buildNewMessageObject` function that:
1. Creates a variable for all the existing messages int he message data file.
1. Creates a new object with the data received from the input files in the navbar (for now: input text field; later on we will add the user id and the timestamp). 
1. Calls the setter method noted below from the messageData file in order to update the array of messages in the function to include this latest message object. created. 
1. Resets the value of the input text field to an empty string. 
1. Calls the displayAllMessages function from the displayMessages file which will build the domString for the messages' container. 
* Then export the `addMessage`function out of this file. 
* In the messages data file, add a setter method that uses this function to add the newly submitted message to the array of messages (use push method) and then export that setter method so that it can be used in the full display of messages. 
* In the navbar.js (where the input field is created), add a function for the keypress event: Write an event listener for the keypress event of pressing Enter (ascii code 13). See link below for some tips. 
* Note: This function builds a card that will then be pulled into the displayMessages component with ticket #17 . That's where the domString for the individual message card gets built - with the content of the message from the Input field. One more note: Other tickets will add more components to this domString: user name (this is done in the tickets for Multiple Users #6 /MessageUsers #18 ), timestamp (this is done in the Timestamp ticket #8 ), and Delete button (this is done in the Delete Message ticket #16 ). ]

**Comment by ancasimon** [comment]
Pressing Enter using the `keypress` event:
https://www.tutorialrepublic.com/faq/how-to-detect-the-enter-key-press-in-a-text-input-field-using-jquery.php

**Comment by ancasimon** [comment]
Possible Bootstrap card template (take out button  - or move it to use as the Delete button):
```
<div class="card text-center">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
  <div class="card-footer text-muted">
    2 days ago
  </div>
</div>
```

**Comment by sarahholder** [comment]
Anca - I found a .`validate()` that we will probably need to use in some fashion to make sure the message isn't submitted before the radio button is selected. It seems like it would be added on this ticket here, but if not you or I can move it to the appropriate ticket.
https://stackoverflow.com/questions/39577367/how-to-add-form-validation-on-group-of-radio-button-using-jquery-form-validation

**Comment by ancasimon** [comment]
Great point Sarah!
We would also need to validate that there is text in the message so that you can't just add a blank message - if you are online, feel free to add these notes to the AddMessage ticket. They don't have to be detailed - just what we have here is great.

I am planning to work on this tonight so I will incorporate this then!

Thanks!

Anca

**Comment by ancasimon** [comment]
Moved the validation to a new ticket: #46
