### ISSUE TITLE
Clear Messages

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-sundews#14]
## User Story
As a user, when I have messages, I should be able to clear them out with a single button.

As a user, when I DON'T have messages, I should not be able to click the clear button

## AC
**Given** A user navigates to your page
**Then** they see a bunch of messages
**And** they click the clear button
**And** the chat history should get cleared out

**Given** A user navigates to your page
**And** they see no messages
**Then** the clear button should be disabled.

## Dev Notes
* In the navbar.js file, in the domString that builds the navbar:
1. Add a unique id to the Clear button: `btn-clear`. 
1. Add the `disableClearButton` function that disables the button - see site linked below for tips. Define a `clearButton` variable for the button using a selector, then add an if statement that controls how the Clear button displays: if the number of messages (note from John: look inside the div and check the innerHtml to see if there's any content in there) is > 0, then the `clearButton.disabled` property is set to false; if the number of messages === 0, then the `clearButton.disabled` property is set to true. 
1. Add the function to the domString that builds the navbar and the Clear button. 
* Create a new component `clearMessages` with 2 files: `clearMessages.js` and `clearMessages.scss`.
* In the `clearMessages.js` file:
1. Write the `clearMessages` function, which builds an empty domString and returns it. 
1. Write the `clearButtonEvent` function that adds an event listener to the Clear button id so that, when clicked, it calls the `clearMessages` function. (maybe:  `$('body').on('click', '#btn-clear', clearMessages());`).
1. Export both functions. 
1. Import both functions into the `main.js` file and add them to the `init()` function.

**Comment by ancasimon** [comment]
This ticket depends on #1 , which adds the button to the navbar.

**Comment by ancasimon** [comment]
An option for disabling the Clear button using Javascript: https://flaviocopes.com/how-to-disable-button-javascript/

**Comment by ancasimon** [comment]
Note for me: Still have to disable button!
