### ISSUE TITLE
Large Text

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-sundews#15]
## User Story
As a user, with tired eyes, I should be able to chat with large text.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Large Text"
**And** they should be able to click this checkbox
**And** when the checkbox is selected all the message text should be larger

## Dev Notes
* Create a ```largeText``` folder
* Create the proper largeText ```js``` and ```scss``` files
* Create a class of ```.large-font``` in the ```scss``` with the font-size set to 25px;
* Create a ```largeText``` function:
 1. Target the parent container
 1. Add an if statement to see if the checkbox is selected or not. If so then run the function and if not then do nothing
 1. Add the ```.large-font``` to the parent-container

**Comment by Jmarquez8951** [comment]
https://www.digitalocean.com/community/tutorials/how-to-modify-attributes-classes-and-styles-in-the-dom
