### ISSUE TITLE
Display Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-sundews#17]
## User Story
As a user, when the page loads, I should see messages.

## AC
**Given** A user navigates to your page
**Then** they should see the 5 messages from `helpers/data/messageData.js`
**And** when they add messages it should add them to the list

## Dev Notes
* Create a folder called displayMessage with two files: displayMessage.js and displayMessage.scss inside of javascripts/components

* Create a function called `displayAllMessages` that does the following:
1. Creates a variable that pulls all the existing messages (there should be a get method in the messages data file that you can use to set this new variable). 
1. Builds a domString that includes a div container. 
1. Does a forEach loop for all existing messages. 
1. Adds new content to the domString from each message card. Note: make sure you use the setter method from the messages data file to make sure we grab the latest version of the array of messages. 
1. Uses printToDom from utilities.js.
* Import utilities for `printToDom` function. 
* Import messages' seed data from the data file. 
* Import individual messages' cards from the `addMessage.js` file.

**Comment by ancasimon** [comment]
shdfjklsdf

**Comment by sarahholder** [comment]
Mary:  Zoe is like a sundew flower with her twitchy habits of being negative and always picking on me.
Luke:  Yeah her sweet side draws people in but then she devours them.
Mary:  I think she is about to devour me then.
Zoe: Did someone say PIE? 
John:  Hey Zoe your students want to know if their site needs a meta tag. 
Zoe:  The way they code a toe tag would be more appropriate.

**Comment by John-Ryan-Johnson** [comment]
see wireframe

**Comment by Jmarquez8951** [comment]
👍
