### ISSUE TITLE
Seed Data

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-sundews#3]
## User Story
As a developer, in order to have something on the page, I would like some seed data

## AC
**Given** A developer navigated to your repo
**Then** they should see a file called `helpers/data/messageData.js`
**And** this file should have seed data for 5 messages

## Dev Notes
* create an array of objects called messages
* objects should include: userId, name, time stamp, message
* fill in dummy data for the first 5 objects
* write a getMessages function that returns the messages array
* export getMessages

**Comment by ancasimon** [comment]
Zoe indicated that we could add code to the getter method for the messages' seed data that pulls only the last 20 messages so that only these get displayed.

**Comment by sarahholder** [comment]
Mary:  Zoe is like a sundew plant with her twitchy habits-- she seems nice and then "SNAP" and she strikes.
Luke:  Yeah, her sweet side draws people in but then she devours them.
Mary:  I think she is about to devour me, maybe I should bring her pie.
Zoe: Did someone say PIE?
John:  Is pie the only thing on your mind? Listen your students need to know their sites need to include a meta tag. 
Zoe:  The way they code a toe tag would be more appropriate.
