### ISSUE TITLE
Message Limit

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-sundews#7]
## User Story
As a user, I have a short attention span, and only want to see the last 20 messages.

## AC
**Given** A user navigates to your page
**Then** they should only see the last 20 messages

## Dev Notes
* Create a ```getMessageLimitArray``` function in the data file
* Export ```getMessageLimitArray```
* Create a ```messageLimit``` folder
* Create the proper messageLimit ```js``` and ```scss``` files
* In your messageLimit.js file import your ```messagesData``` array
* Create a ```messageLimit``` function:
 1. Assign the ```messageDataArray``` its own variable using ```let```
 1. Grab the last 20 messages from the array using the splice method
 1. Push them into the ```messageLimitArray```
 1. Print the ```messageLimitArray``` using the ```printToDom``` function from the ```utils.js```
 1. Export the ```messageLimit``` function

**Comment by Jmarquez8951** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

**Comment by John-Ryan-Johnson** [comment]
Ref display message
