### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-sundews#8]
## User Story
As a user, using all the chatting sites, I always see clean looking timestamps.

**Dirty Timestamp:**  2014-09-08T08:02:17-05:00
**Clean Timestamp:**  September 8, 2014 8:02 PM

## AC
**Given** A user navigates to your page
**Then** they see all the messages
**And**  the messages should have nice looking timestamps

## Dev Notes
* Real JS developers hate dates - they use a magical library called [MomentJS](https://momentjs.com/)
```js
npm install moment --save
```
* In the `displayMessages.js` file > In the domString that displays the message (inside the forEach loop?), add a `<p>` tag that includes the `moment.js` code below. 
* Maybe: `domString += <p>${moment(message.date).format(('MMMM Do YYYY, h:mm:ss a')}`.
* Make sure to test that the timestamp is static - once set on a message, it should not get changed when a new message is submitted. 
* Stretch goal: separate the date and the time - (1)have one function that pulls the date and displays it outside of the messages - at the top, above the messages - - and then (2)a second function that pulls the time when the message is added and displays it inside the message, at the bottom of the message.

**Comment by ancasimon** [comment]
This is the moment.js function we need to display  March 9th 2020, 8:03:39 pm:
```
moment().format('MMMM Do YYYY, h:mm:ss a')
```

**Comment by ancasimon** [comment]
Here's the example from the dino-kennel project: `domString += `<td>${moment(advArray[i].date).format('MMMM Do YYYY, h:mm:ss a')}</td>`;`
